print("Hello Milana!")
print(input("what is your name?"))
print(input("what is your age?"))
print(input("what is your height?"))
print(input("what is your weight?"))
print(input("what is your favorite color?"))
print(input("what is your favorite color?"))
print(input("what is your favorite color?"))
print(input("what is your favorite color?"))